/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ShowBooks;
import dao.SachDAO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Toolkit;
import java.net.URL;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Sach;

/**
 *
 * @author HOANG TIEN THUAN
 */
public class Home extends javax.swing.JFrame {

    DefaultTableModel tableModel;

    public Home() {
        initComponents();
        tableModel = (DefaultTableModel) tbl_Sach.getModel();
        ShowBook();
        resetTxtSearchBook();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/logo.png")));
        setVisible();
    }

    public void ShowBook() {
        List<Sach> listSach = SachDAO.getInstant().selectAll();
        tableModel.setRowCount(0);
        listSach.forEach((sach) -> {
            tableModel.addRow(new Object[]{sach.getId(),
                sach.getTenSach(),sach.getTheLoai(), sach.getTacGia(), sach.getNamXB(),
                sach.getNhaXB(), sach.getSoLuong(), sach.getGiaSach()});
        });

    }

    public void resetFontColor() {
        lb_QuanLySach.setForeground(Color.WHITE);
        lb_QuanLyDocGia.setForeground(Color.WHITE);
        lb_PhieuMuon.setForeground(Color.WHITE);
        lb_ThongKeBaoCao.setForeground(Color.WHITE);
    }

    public void setVisible() {
        rightPanelDocGia.setVisible(false);
        rightPanelSach.setVisible(false);
        rightPanelPhieuMuon.setVisible(false);
        rightPanelThongke.setVisible(false);
    }

    public void resetTxtSearchBook() {
        lb_SearchDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png")));
        lb_SearchDocGia.setText(" Tìm kiếm sách");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightPanelDocGia = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_DocGia = new javax.swing.JTable();
        btm_editDocGia = new javax.swing.JButton();
        lb_IdDocGia = new javax.swing.JLabel();
        txtTenDocGia = new javax.swing.JTextField();
        lb_TenDocGia = new javax.swing.JLabel();
        txtIdDocGia = new javax.swing.JTextField();
        lb_gender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lb_ngaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        lb_cccd = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        lb_bookQuantity1 = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btn_delBook1 = new javax.swing.JButton();
        btn_insertBook1 = new javax.swing.JButton();
        lb_SortBy1 = new javax.swing.JLabel();
        cbxSortDocGia = new javax.swing.JComboBox<>();
        SearchDocGia = new javax.swing.JPanel();
        lb_SearchDocGia = new javax.swing.JLabel();
        txtSearchDocGia = new javax.swing.JTextField();
        Home = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        HeadingHome = new javax.swing.JLabel();
        pnl_PhieuMuon = new javax.swing.JPanel();
        lb_PhieuMuon = new javax.swing.JLabel();
        pnl_Thongkebaocao = new javax.swing.JPanel();
        lb_ThongKeBaoCao = new javax.swing.JLabel();
        pnl_QuanLyDocGia = new javax.swing.JPanel();
        lb_QuanLyDocGia = new javax.swing.JLabel();
        pnl_QuanLySach = new javax.swing.JPanel();
        lb_QuanLySach = new javax.swing.JLabel();
        logOutIcon = new javax.swing.JLabel();
        bground = new javax.swing.JLabel();
        rightPanelSach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Sach = new javax.swing.JTable();
        btm_editBook = new javax.swing.JButton();
        lb_IdBook = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        lb_bookName = new javax.swing.JLabel();
        txtIdBook = new javax.swing.JTextField();
        lb_author = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();
        lb_publisher = new javax.swing.JLabel();
        txtPublisher = new javax.swing.JTextField();
        lb_publishYear = new javax.swing.JLabel();
        txtPublishYear = new javax.swing.JTextField();
        lb_bookQuantity = new javax.swing.JLabel();
        lb_typeOfBook = new javax.swing.JLabel();
        txtTypeOfBook = new javax.swing.JTextField();
        lb_price = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        spiner_bookQuantity = new javax.swing.JSpinner();
        btn_delBook = new javax.swing.JButton();
        btn_insertBook = new javax.swing.JButton();
        lb_SortBy = new javax.swing.JLabel();
        cbxSortBook = new javax.swing.JComboBox<>();
        SearchBook = new javax.swing.JPanel();
        lb_SearchBook = new javax.swing.JLabel();
        txtSearchBook = new javax.swing.JTextField();
        rightPanelPhieuMuon = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_PhieuMuon = new javax.swing.JTable();
        lb_search = new javax.swing.JLabel();
        lb_IdBook1 = new javax.swing.JLabel();
        txtMaPhieuMuon = new javax.swing.JTextField();
        lb_IdBook2 = new javax.swing.JLabel();
        txtIdBook2 = new javax.swing.JTextField();
        lb_IdBook3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        btn_insertBook2 = new javax.swing.JButton();
        btm_editBook1 = new javax.swing.JButton();
        btn_delBook2 = new javax.swing.JButton();
        rightPanelThongke = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - Library Management System");
        setResizable(false);

        rightPanelDocGia.setBackground(new java.awt.Color(204, 255, 255));
        rightPanelDocGia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_DocGia.setBackground(new java.awt.Color(153, 255, 153));
        tbl_DocGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_DocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đôc giả", "Họ tên", "Giói tính", "Ngày sinh", "CCCD/CMND", "Số điện thoại", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_DocGia.setGridColor(new java.awt.Color(0, 51, 51));
        jScrollPane2.setViewportView(tbl_DocGia);

        rightPanelDocGia.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 367, 990, 360));

        btm_editDocGia.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btm_editDocGia.setText("Sửa");
        rightPanelDocGia.add(btm_editDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 310, 108, 39));

        lb_IdDocGia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_IdDocGia.setText("Mã độc giả");
        rightPanelDocGia.add(lb_IdDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 84, 82, -1));

        txtTenDocGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanelDocGia.add(txtTenDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 131, 195, 32));

        lb_TenDocGia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_TenDocGia.setText("Họ và tên");
        rightPanelDocGia.add(lb_TenDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 134, 82, -1));

        txtIdDocGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanelDocGia.add(txtIdDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 81, 195, 32));

        lb_gender.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_gender.setText("Giới tính");
        rightPanelDocGia.add(lb_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 184, 82, -1));

        txtGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanelDocGia.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 181, 195, 32));

        lb_ngaySinh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_ngaySinh.setText("Ngày sinh");
        rightPanelDocGia.add(lb_ngaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 234, 106, -1));

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanelDocGia.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 231, 195, 32));

        lb_cccd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_cccd.setText("Số CCCD");
        rightPanelDocGia.add(lb_cccd, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 84, -1, -1));

        txtCCCD.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rightPanelDocGia.add(txtCCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 81, 195, 32));

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rightPanelDocGia.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 195, 32));

        lb_bookQuantity1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_bookQuantity1.setText("Số điện thoại");
        rightPanelDocGia.add(lb_bookQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 131, 97, 26));

        lb_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_email.setText("Email");
        rightPanelDocGia.add(lb_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 184, 82, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanelDocGia.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 181, 195, 32));

        btn_delBook1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_delBook1.setText("Xóa");
        rightPanelDocGia.add(btn_delBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 310, 108, 39));

        btn_insertBook1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_insertBook1.setText("Thêm");
        btn_insertBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertBook1ActionPerformed(evt);
            }
        });
        rightPanelDocGia.add(btn_insertBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 310, 108, 39));

        lb_SortBy1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_SortBy1.setText("Sắp xếp theo: ");
        rightPanelDocGia.add(lb_SortBy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 318, -1, -1));

        cbxSortDocGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxSortDocGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã", "Tên", "Giới tính" }));
        rightPanelDocGia.add(cbxSortDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 317, 117, -1));

        SearchDocGia.setBackground(new java.awt.Color(204, 255, 255));
        SearchDocGia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_SearchDocGia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lb_SearchDocGia.setForeground(new java.awt.Color(153, 153, 153));
        lb_SearchDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        lb_SearchDocGia.setText(" Tìm kiếm độc giả");
        lb_SearchDocGia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SearchDocGia.add(lb_SearchDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 150, 20));

        txtSearchDocGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchDocGia.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchDocGiaCaretUpdate(evt);
            }
        });
        txtSearchDocGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchDocGiaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchDocGiaFocusLost(evt);
            }
        });
        txtSearchDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDocGiaActionPerformed(evt);
            }
        });
        SearchDocGia.add(txtSearchDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 37));

        rightPanelDocGia.add(SearchDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 32, -1, -1));

        Home.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Hello, Admin.");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel1)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeadingHome.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
        HeadingHome.setForeground(new java.awt.Color(255, 255, 255));
        HeadingHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadingHome.setText("LMS");
        leftPanel.add(HeadingHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        pnl_PhieuMuon.setBackground(new java.awt.Color(255, 204, 51));

        lb_PhieuMuon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_PhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        lb_PhieuMuon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_PhieuMuon.setText("Quản lý phiếu mượn");
        lb_PhieuMuon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb_PhieuMuon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_PhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_PhieuMuonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_PhieuMuonLayout = new javax.swing.GroupLayout(pnl_PhieuMuon);
        pnl_PhieuMuon.setLayout(pnl_PhieuMuonLayout);
        pnl_PhieuMuonLayout.setHorizontalGroup(
            pnl_PhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PhieuMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_PhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_PhieuMuonLayout.setVerticalGroup(
            pnl_PhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PhieuMuonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_PhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        leftPanel.add(pnl_PhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        pnl_Thongkebaocao.setBackground(new java.awt.Color(255, 102, 102));

        lb_ThongKeBaoCao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_ThongKeBaoCao.setForeground(new java.awt.Color(255, 255, 255));
        lb_ThongKeBaoCao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ThongKeBaoCao.setText("Thống kê");
        lb_ThongKeBaoCao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb_ThongKeBaoCao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_ThongKeBaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ThongKeBaoCaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_ThongkebaocaoLayout = new javax.swing.GroupLayout(pnl_Thongkebaocao);
        pnl_Thongkebaocao.setLayout(pnl_ThongkebaocaoLayout);
        pnl_ThongkebaocaoLayout.setHorizontalGroup(
            pnl_ThongkebaocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ThongkebaocaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_ThongKeBaoCao, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_ThongkebaocaoLayout.setVerticalGroup(
            pnl_ThongkebaocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ThongkebaocaoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_ThongKeBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        leftPanel.add(pnl_Thongkebaocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        pnl_QuanLyDocGia.setBackground(new java.awt.Color(0, 204, 51));

        lb_QuanLyDocGia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_QuanLyDocGia.setForeground(new java.awt.Color(255, 255, 255));
        lb_QuanLyDocGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_QuanLyDocGia.setText("Quản lý độc giả");
        lb_QuanLyDocGia.setToolTipText("Poison management function");
        lb_QuanLyDocGia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb_QuanLyDocGia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_QuanLyDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_QuanLyDocGiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_QuanLyDocGiaLayout = new javax.swing.GroupLayout(pnl_QuanLyDocGia);
        pnl_QuanLyDocGia.setLayout(pnl_QuanLyDocGiaLayout);
        pnl_QuanLyDocGiaLayout.setHorizontalGroup(
            pnl_QuanLyDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(pnl_QuanLyDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_QuanLyDocGiaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lb_QuanLyDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_QuanLyDocGiaLayout.setVerticalGroup(
            pnl_QuanLyDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(pnl_QuanLyDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_QuanLyDocGiaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lb_QuanLyDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        leftPanel.add(pnl_QuanLyDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        pnl_QuanLySach.setBackground(new java.awt.Color(241, 157, 97));

        lb_QuanLySach.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_QuanLySach.setForeground(new java.awt.Color(255, 255, 255));
        lb_QuanLySach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_QuanLySach.setText("Quản lý sách");
        lb_QuanLySach.setToolTipText("Book management function");
        lb_QuanLySach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb_QuanLySach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_QuanLySach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_QuanLySachMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_QuanLySachMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnl_QuanLySachLayout = new javax.swing.GroupLayout(pnl_QuanLySach);
        pnl_QuanLySach.setLayout(pnl_QuanLySachLayout);
        pnl_QuanLySachLayout.setHorizontalGroup(
            pnl_QuanLySachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_QuanLySachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_QuanLySach, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_QuanLySachLayout.setVerticalGroup(
            pnl_QuanLySachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_QuanLySach, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        leftPanel.add(pnl_QuanLySach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        logOutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-logout-24.png"))); // NOI18N
        leftPanel.add(logOutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 685, -1, 30));

        bground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/splashBG.jpg"))); // NOI18N
        leftPanel.add(bground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rightPanelSach.setBackground(new java.awt.Color(255, 204, 153));

        tbl_Sach.setBackground(new java.awt.Color(204, 204, 204));
        tbl_Sach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_Sach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Thể loại", "Tác giả", "Năm xuất bản", "Nhà xuất bản", "Số lượng", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_Sach.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_Sach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_Sach);
        if (tbl_Sach.getColumnModel().getColumnCount() > 0) {
            tbl_Sach.getColumnModel().getColumn(4).setResizable(false);
        }

        btm_editBook.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btm_editBook.setText("Sửa");

        lb_IdBook.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_IdBook.setText("Mã sách");

        txtBookName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lb_bookName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_bookName.setText("Tên sách");

        txtIdBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBookActionPerformed(evt);
            }
        });

        lb_author.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_author.setText("Tác giả");

        txtAuthor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lb_publisher.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_publisher.setText("Nhà xuất bản");

        txtPublisher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lb_publishYear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_publishYear.setText("Năm xuất bản");

        txtPublishYear.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        lb_bookQuantity.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_bookQuantity.setText("Số lượng");

        lb_typeOfBook.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_typeOfBook.setText("Thể loại");

        txtTypeOfBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lb_price.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_price.setText("Giá");

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        spiner_bookQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spiner_bookQuantity.setPreferredSize(new java.awt.Dimension(60, 26));

        btn_delBook.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_delBook.setText("Xóa");

        btn_insertBook.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_insertBook.setText("Thêm");
        btn_insertBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertBookActionPerformed(evt);
            }
        });

        lb_SortBy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_SortBy.setText("Sắp xếp theo: ");

        cbxSortBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxSortBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã sách", "Tên sách", "Tác giả", "Nhà xuất bản", "Số lượng", "Thể loại", "Giá" }));

        SearchBook.setBackground(new java.awt.Color(255, 204, 153));

        lb_SearchBook.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lb_SearchBook.setForeground(new java.awt.Color(153, 153, 153));
        lb_SearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        lb_SearchBook.setText(" Tìm kiếm sách");

        txtSearchBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchBook.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchBookCaretUpdate(evt);
            }
        });
        txtSearchBook.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchBookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchBookFocusLost(evt);
            }
        });
        txtSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchBookLayout = new javax.swing.GroupLayout(SearchBook);
        SearchBook.setLayout(SearchBookLayout);
        SearchBookLayout.setHorizontalGroup(
            SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBookLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lb_SearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(txtSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        SearchBookLayout.setVerticalGroup(
            SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBookLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lb_SearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(txtSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout rightPanelSachLayout = new javax.swing.GroupLayout(rightPanelSach);
        rightPanelSach.setLayout(rightPanelSachLayout);
        rightPanelSachLayout.setHorizontalGroup(
            rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelSachLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelSachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(rightPanelSachLayout.createSequentialGroup()
                        .addComponent(lb_author, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(lb_typeOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(txtTypeOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightPanelSachLayout.createSequentialGroup()
                        .addComponent(lb_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(lb_price, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightPanelSachLayout.createSequentialGroup()
                        .addComponent(btn_insertBook, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(btm_editBook, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btn_delBook, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(lb_SortBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxSortBook, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightPanelSachLayout.createSequentialGroup()
                        .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightPanelSachLayout.createSequentialGroup()
                                .addComponent(lb_bookName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(rightPanelSachLayout.createSequentialGroup()
                                    .addComponent(lb_IdBook, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(txtIdBook, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(SearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(161, 161, 161)
                        .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_bookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_publishYear))
                        .addGap(90, 90, 90)
                        .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPublishYear, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spiner_bookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68))
        );
        rightPanelSachLayout.setVerticalGroup(
            rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelSachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdBook, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPublishYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_publishYear))
                    .addGroup(rightPanelSachLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lb_IdBook)))
                .addGap(18, 18, 18)
                .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanelSachLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lb_bookName))
                    .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_bookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiner_bookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTypeOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightPanelSachLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_author)
                            .addComponent(lb_typeOfBook))))
                .addGap(18, 18, 18)
                .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightPanelSachLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_publisher)
                            .addComponent(lb_price))))
                .addGap(47, 47, 47)
                .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_insertBook, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_editBook, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delBook, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightPanelSachLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(rightPanelSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxSortBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_SortBy))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rightPanelPhieuMuon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_PhieuMuon.setBackground(new java.awt.Color(204, 204, 255));
        tbl_PhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu mượn", "Mã ĐG", "Số lượng", "Ngày mượn", "Ngày hẹn trả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_PhieuMuon);

        rightPanelPhieuMuon.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 369, 990, 350));
        rightPanelPhieuMuon.add(lb_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 20, 20));

        lb_IdBook1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_IdBook1.setText("Mã PM");
        rightPanelPhieuMuon.add(lb_IdBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, -1));

        txtMaPhieuMuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaPhieuMuon.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtMaPhieuMuonCaretUpdate(evt);
            }
        });
        txtMaPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhieuMuonActionPerformed(evt);
            }
        });
        rightPanelPhieuMuon.add(txtMaPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 76, 195, 32));

        lb_IdBook2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_IdBook2.setText("Mã DG");
        rightPanelPhieuMuon.add(lb_IdBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 80, -1));

        txtIdBook2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdBook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBook2ActionPerformed(evt);
            }
        });
        rightPanelPhieuMuon.add(txtIdBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 146, 195, 32));

        lb_IdBook3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lb_IdBook3.setText("Số lượng");
        rightPanelPhieuMuon.add(lb_IdBook3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 216, 80, -1));

        jSpinner1.setPreferredSize(new java.awt.Dimension(70, 25));
        rightPanelPhieuMuon.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 217, 55, -1));

        btn_insertBook2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_insertBook2.setText("Thêm");
        btn_insertBook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertBook2ActionPerformed(evt);
            }
        });
        rightPanelPhieuMuon.add(btn_insertBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 297, 108, 39));

        btm_editBook1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btm_editBook1.setText("Sửa");
        rightPanelPhieuMuon.add(btm_editBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 297, 108, 39));

        btn_delBook2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_delBook2.setText("Xóa");
        rightPanelPhieuMuon.add(btn_delBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 297, 108, 39));

        rightPanelThongke.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout rightPanelThongkeLayout = new javax.swing.GroupLayout(rightPanelThongke);
        rightPanelThongke.setLayout(rightPanelThongkeLayout);
        rightPanelThongkeLayout.setHorizontalGroup(
            rightPanelThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        rightPanelThongkeLayout.setVerticalGroup(
            rightPanelThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanelThongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightPanelPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightPanelDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(rightPanelSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(rightPanelThongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(rightPanelPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(rightPanelDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(rightPanelSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_insertBookActionPerformed

    private void lb_QuanLySachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_QuanLySachMouseClicked
        this.setTitle("Books - Library Management System");
        setVisible();
        rightPanelSach.setVisible(true);
        resetFontColor();
        lb_QuanLySach.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb_QuanLySachMouseClicked

    private void lb_QuanLyDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_QuanLyDocGiaMouseClicked
        this.setTitle("Readers - Library Management System");
        setVisible();
        rightPanelDocGia.setVisible(true);
        resetFontColor();
        lb_QuanLyDocGia.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb_QuanLyDocGiaMouseClicked

    private void lb_QuanLySachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_QuanLySachMouseEntered

    }//GEN-LAST:event_lb_QuanLySachMouseEntered

    private void txtIdBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBookActionPerformed

    private void txtMaPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhieuMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhieuMuonActionPerformed

    private void txtIdBook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBook2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBook2ActionPerformed

    private void btn_insertBook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertBook2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_insertBook2ActionPerformed

    private void lb_PhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_PhieuMuonMouseClicked
        this.setTitle("Loan Slip - Library Management System");
        setVisible();
        rightPanelPhieuMuon.setVisible(true);
//        rightPanelSach.setVisible(false);
//        rightPanelDocGia.setVisible(false);
//        rightPanelThongke.setVisible(false);
        resetFontColor();
        lb_PhieuMuon.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb_PhieuMuonMouseClicked

    private void lb_ThongKeBaoCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ThongKeBaoCaoMouseClicked
        this.setTitle("Analysis - Library Management System");
        setVisible();
        rightPanelThongke.setVisible(true);
//        rightPanelSach.setVisible(false);
//        rightPanelDocGia.setVisible(false);
//        rightPanelPhieuMuon.setVisible(false);
        resetFontColor();
        lb_ThongKeBaoCao.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb_ThongKeBaoCaoMouseClicked

    private void txtSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchBookActionPerformed

    private void txtSearchBookCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchBookCaretUpdate
//        if (txtSearchBook.getText().length() != 0) {
//            lb_SearchBook.setIcon(null);
//            lb_SearchBook.setText("");
//        } else {
//            lb_SearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png")));
//            lb_SearchBook.setText(" Tìm kiếm sách");
//        }
    }//GEN-LAST:event_txtSearchBookCaretUpdate

    private void txtSearchDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDocGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchDocGiaActionPerformed

    private void txtSearchDocGiaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchDocGiaCaretUpdate
//        if (txtSearchDocGia.getText().length() != 0) {
//            lb_SearchDocGia.setIcon(null);
//            lb_SearchDocGia.setText("");
//        } else {
//            lb_SearchDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png")));
//            lb_SearchDocGia.setText(" Tìm kiếm độc giả");
//        }
    }//GEN-LAST:event_txtSearchDocGiaCaretUpdate

    private void btn_insertBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertBook1ActionPerformed
        // TODO add your handling code here:ss
    }//GEN-LAST:event_btn_insertBook1ActionPerformed

    private void txtSearchDocGiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchDocGiaFocusGained
        if (txtSearchDocGia.getText().length() != 0) {
            lb_SearchDocGia.setIcon(null);
            lb_SearchDocGia.setText("");
        } else {
            lb_SearchDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png")));
            lb_SearchDocGia.setText(" Tìm kiếm độc giả");
        }
    }//GEN-LAST:event_txtSearchDocGiaFocusGained

    private void txtSearchDocGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchDocGiaFocusLost
        if (txtSearchDocGia.getText().length() != 0) {
            lb_SearchDocGia.setIcon(null);
            lb_SearchDocGia.setText("");
        } else {
            lb_SearchDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png")));
            lb_SearchDocGia.setText(" Tìm kiếm độc giả");
        }
    }//GEN-LAST:event_txtSearchDocGiaFocusLost

    private void txtMaPhieuMuonCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtMaPhieuMuonCaretUpdate

    }//GEN-LAST:event_txtMaPhieuMuonCaretUpdate

    private void txtSearchBookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchBookFocusGained
        if (txtSearchBook.getText().length() != 0) {
            lb_SearchBook.setIcon(null);
            lb_SearchBook.setText("");
        } else {
            lb_SearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png")));
            lb_SearchBook.setText(" Tìm kiếm sách");
        }
    }//GEN-LAST:event_txtSearchBookFocusGained

    private void txtSearchBookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchBookFocusLost
        if (txtSearchDocGia.getText().length() != 0) {
            lb_SearchDocGia.setIcon(null);
            lb_SearchDocGia.setText("");
        } else {
            lb_SearchDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png")));
            lb_SearchDocGia.setText(" Tìm kiếm sách");
        }
    }//GEN-LAST:event_txtSearchBookFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    public JLabel getHeadingHome() {
        return HeadingHome;
    }

    public JLabel getBground() {
        return bground;
    }

    public JButton getBtm_editBook() {
        return btm_editBook;
    }

    public JButton getBtm_editDocGia() {
        return btm_editDocGia;
    }

    public JButton getBtn_delBook() {
        return btn_delBook;
    }

    public JButton getBtn_delBook1() {
        return btn_delBook1;
    }

    public JButton getBtn_insertBook() {
        return btn_insertBook;
    }

    public JButton getBtn_insertBook1() {
        return btn_insertBook1;
    }

    public JComboBox<String> getCbxSortBook() {
        return cbxSortBook;
    }

    public JComboBox<String> getCbxSortDocGia() {
        return cbxSortDocGia;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JLabel getLb_IdBook() {
        return lb_IdBook;
    }

    public JLabel getLb_IdDocGia() {
        return lb_IdDocGia;
    }

    public JLabel getLb_QuanLyDocGia() {
        return lb_QuanLyDocGia;
    }

    public JLabel getLb_QuanLySach() {
        return lb_QuanLySach;
    }

    public JLabel getLb_SortBy() {
        return lb_SortBy;
    }

    public JLabel getLb_SortBy1() {
        return lb_SortBy1;
    }

    public JLabel getLb_TenDocGia() {
        return lb_TenDocGia;
    }

    public JLabel getLb_ThongKeBaoCao() {
        return lb_ThongKeBaoCao;
    }

    public JLabel getLb_author() {
        return lb_author;
    }

    public JLabel getLb_bookName() {
        return lb_bookName;
    }

    public JLabel getLb_bookQuantity() {
        return lb_bookQuantity;
    }

    public JLabel getLb_bookQuantity1() {
        return lb_bookQuantity1;
    }

    public JLabel getLb_cccd() {
        return lb_cccd;
    }

    public JLabel getLb_email() {
        return lb_email;
    }

    public JLabel getLb_gender() {
        return lb_gender;
    }

    public JLabel getLb_ngaySinh() {
        return lb_ngaySinh;
    }

    public JLabel getLb_price() {
        return lb_price;
    }

    public JLabel getLb_publishYear() {
        return lb_publishYear;
    }

    public JLabel getLb_publisher() {
        return lb_publisher;
    }

    public JLabel getLb_typeOfBook() {
        return lb_typeOfBook;
    }

    public JPanel getLeftPanel() {
        return leftPanel;
    }

    public JLabel getLogOutIcon() {
        return logOutIcon;
    }

    public JPanel getPnl_QuanLyDocGia() {
        return pnl_QuanLyDocGia;
    }

    public JPanel getPnl_QuanLySach() {
        return pnl_QuanLySach;
    }

    public JPanel getPnl_Thongkebaocao() {
        return pnl_Thongkebaocao;
    }

    public JPanel getRightPanelDocGia() {
        return rightPanelDocGia;
    }

    public JPanel getRightPanelSach() {
        return rightPanelSach;
    }

    public JSpinner getSpiner_bookQuantity() {
        return spiner_bookQuantity;
    }

    public JTable getTbl_DocGia() {
        return tbl_DocGia;
    }

    public JTable getTbl_Sach() {
        return tbl_Sach;
    }

    public JTextField getTxtAuthor() {
        return txtAuthor;
    }

    public JTextField getTxtBookName() {
        return txtBookName;
    }

    public JTextField getTxtCCCD() {
        return txtCCCD;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JTextField getTxtGender() {
        return txtGender;
    }

    public JTextField getTxtIdBook() {
        return txtIdBook;
    }

    public JTextField getTxtIdDocGia() {
        return txtIdDocGia;
    }

    public JTextField getTxtNgaySinh() {
        return txtNgaySinh;
    }

    public JTextField getTxtPrice() {
        return txtPrice;
    }

    public JTextField getTxtPublishYear() {
        return txtPublishYear;
    }

    public JTextField getTxtPublisher() {
        return txtPublisher;
    }

    public JTextField getTxtSDT() {
        return txtSDT;
    }

    public JTextField getTxtTenDocGia() {
        return txtTenDocGia;
    }

    public JTextField getTxtTypeOfBook() {
        return txtTypeOfBook;
    }

    public DefaultTableModel getTableModel() {
        return tableModel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeadingHome;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel SearchBook;
    private javax.swing.JPanel SearchDocGia;
    private javax.swing.JLabel bground;
    private javax.swing.JButton btm_editBook;
    private javax.swing.JButton btm_editBook1;
    private javax.swing.JButton btm_editDocGia;
    private javax.swing.JButton btn_delBook;
    private javax.swing.JButton btn_delBook1;
    private javax.swing.JButton btn_delBook2;
    private javax.swing.JButton btn_insertBook;
    private javax.swing.JButton btn_insertBook1;
    private javax.swing.JButton btn_insertBook2;
    private javax.swing.JComboBox<String> cbxSortBook;
    private javax.swing.JComboBox<String> cbxSortDocGia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lb_IdBook;
    private javax.swing.JLabel lb_IdBook1;
    private javax.swing.JLabel lb_IdBook2;
    private javax.swing.JLabel lb_IdBook3;
    private javax.swing.JLabel lb_IdDocGia;
    private javax.swing.JLabel lb_PhieuMuon;
    private javax.swing.JLabel lb_QuanLyDocGia;
    private javax.swing.JLabel lb_QuanLySach;
    private javax.swing.JLabel lb_SearchBook;
    private javax.swing.JLabel lb_SearchDocGia;
    private javax.swing.JLabel lb_SortBy;
    private javax.swing.JLabel lb_SortBy1;
    private javax.swing.JLabel lb_TenDocGia;
    private javax.swing.JLabel lb_ThongKeBaoCao;
    private javax.swing.JLabel lb_author;
    private javax.swing.JLabel lb_bookName;
    private javax.swing.JLabel lb_bookQuantity;
    private javax.swing.JLabel lb_bookQuantity1;
    private javax.swing.JLabel lb_cccd;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_gender;
    private javax.swing.JLabel lb_ngaySinh;
    private javax.swing.JLabel lb_price;
    private javax.swing.JLabel lb_publishYear;
    private javax.swing.JLabel lb_publisher;
    private javax.swing.JLabel lb_search;
    private javax.swing.JLabel lb_typeOfBook;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logOutIcon;
    private javax.swing.JPanel pnl_PhieuMuon;
    private javax.swing.JPanel pnl_QuanLyDocGia;
    private javax.swing.JPanel pnl_QuanLySach;
    private javax.swing.JPanel pnl_Thongkebaocao;
    private javax.swing.JPanel rightPanelDocGia;
    private javax.swing.JPanel rightPanelPhieuMuon;
    private javax.swing.JPanel rightPanelSach;
    private javax.swing.JPanel rightPanelThongke;
    private javax.swing.JSpinner spiner_bookQuantity;
    private javax.swing.JTable tbl_DocGia;
    private javax.swing.JTable tbl_PhieuMuon;
    private javax.swing.JTable tbl_Sach;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtIdBook;
    private javax.swing.JTextField txtIdBook2;
    private javax.swing.JTextField txtIdDocGia;
    private javax.swing.JTextField txtMaPhieuMuon;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPublishYear;
    private javax.swing.JTextField txtPublisher;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSearchBook;
    private javax.swing.JTextField txtSearchDocGia;
    private javax.swing.JTextField txtTenDocGia;
    private javax.swing.JTextField txtTypeOfBook;
    // End of variables declaration//GEN-END:variables
}
